// ═══════════════════════════════════════════════════════════════
// ACTS OF LIFE — every user-facing string lives here.
// Two registers, one voice: backward, a warm curious historian;
// forward, a flat, precise, quietly demanding editor.
// No exclamation marks. Verdicts are placements, never judgments.
// tools/lint_strings.py checks this file against the banned vocabulary.
// ═══════════════════════════════════════════════════════════════

export const S = {
  app: {
    name: 'Acts of Life',
    tagline: 'Your days are full. Your story isn’t.',
  },

  // ── The intro: expectations, vocabulary, mechanics — before anything ──
  intro: {
    t1: 'Your days are full. Your story isn’t.',
    b1a: 'Most apps help you manage your days — the list, the inbox, the reminders. This one is for your life.',
    b1b: 'Acts of Life helps you rise above the daily minutiae, see the big picture of your own story, and chart a better one.',
    t2: 'A life has three altitudes.',
    alt1Name: 'Maintenance',
    alt1: 'The chores, admin, and rituals that keep everything running. Cyclical, never finished, quietly essential. Drawn as small circles along the ground.',
    alt2Name: 'Work',
    alt2: 'The long efforts that leave something behind — a craft, a company, a home, a person raised. Drawn as lines across the middle.',
    alt3Name: 'Acts',
    alt3: 'The rare deeds that begin something new: chosen freely, with something real at risk, felt by other people, impossible to take back. A whole life holds surprisingly few. They are what a story is made of. Drawn as stars in the sky.',
    alt4Name: 'Turnings',
    alt4: 'The inward hinges — when something changed in you before it showed in the world. Drawn as crescents, beside the stars, with equal dignity.',
    t3: 'What this app will never do.',
    b3a: 'No confetti. No applause. No little numbers begging you to come back. No comparing you with anyone. No judgment of your past — ever.',
    b3b: 'One weekly Mirror, one date you set yourself, and otherwise silence. The only thing this app accumulates is your story.',
    t4: 'One choice before we begin.',
    b4: 'The app asks you questions to draw your arc. It can ask them two ways.',
    aiNo: 'Just the app',
    aiNoSub: 'Carefully written questions. Free, fully private — nothing ever leaves this device.',
    aiYes: 'With a second reader',
    aiYesSub: 'Claude, an AI, reads only the entry you’re working on and asks sharper, more personal questions. Uses your own Anthropic key, costs a fraction of a cent per entry, never writes a word of your story.',
    aiKeyAsk: 'Paste your Anthropic API key',
    aiKeyNote: 'Stored only on this device. Change your mind any time in Settings.',
    aiKeyOk: 'The key works.',
    aiKeyBad: 'That key was refused — check it, or continue without.',
    next: 'Continue',
    start: 'Begin',
  },

  arc: {
    quietCaption: 'Most arcs are mostly quiet.',
    now: 'now',
    begin: 'Begin',
    menuMirror: 'Mirror',
    menuLibrary: 'Library',
    menuChapters: 'Chapters',
    menuKept: 'Kept private',
    menuSettings: 'Settings',
    fit: 'Whole arc',
  },

  // ── The tour: shown once the arc first exists ──
  tour: {
    sky: 'This is your arc — your whole life in one scene. Up here, the sky: stars are acts, crescents are turnings. Sparse is normal. Tap any star to read its story.',
    lines: 'The middle band holds your work. Each line is a chapter — its phases mark the road, and one day it ships the thing it was for. Tap a line to open its phases and steps.',
    ground: 'The ground holds maintenance and rituals, drawn small on purpose. What’s due today waits as little rings by the now-line — tap one to mark it kept. Tap anywhere else on the ground to tend the rest.',
    begin: 'Everything enters through Begin — something you did, something you will do, a chapter of work, or the ground.',
    menu: 'And behind this menu: the Mirror, a two-minute weekly look at where the week went. The Library, real examples of small brave acts. Your chapters. Settings. That’s the whole app.',
    next: 'Next',
    done: 'Got it',
  },

  // ── The four tests, explained where they are applied ──
  why: {
    toggle: 'Why this matters',
    beginning: 'An act starts something that was not going to happen without you. The next step of an existing effort — however demanding — belongs to that effort’s line, honourably, as work. Counts: convening the dinner no one asked for. Doesn’t: submitting the report that was due.',
    stake: 'Stake is what you could have lost, judged before you knew how it would go. If nothing real was exposed — money, standing, comfort, a relationship, a self-image — it was safe, and safe things are maintenance or work. A trophy won while risking nothing is a trace of skill, not an act. Attempts that failed with real stake count fully.',
    reach: 'An act lands among other people — it changes something outside your own head, in someone else’s world. Pleasure taken or comfort enjoyed reaches no one; the question is whose life shifted, even slightly. A true hinge that stayed inside you is a turning, drawn as a crescent, with full dignity.',
    irreversible: 'An act cannot be quietly taken back; once done, the world contains it. If you could undo it tomorrow and nobody would ever know, it has not landed yet. The sent letter, the spoken word, the signed name — these are past retrieval.',
  },

  begin: {
    title: 'Begin',
    excavate: 'Something I did',
    excavateSub: 'A moment from your past. We’ll see what it holds.',
    declare: 'Something I will do',
    declareSub: 'A future act, held to a higher bar.',
    chapter: 'A chapter of work',
    chapterSub: 'A bounded effort that will leave something behind.',
    ground: 'Tend the ground',
    groundSub: 'Maintenance and ritual — what keeps the rest possible.',
  },

  // ── Excavation: the generous historian ──
  excavate: {
    title: 'Something you did',
    intro: 'What happened? One or two sentences, the way you’d tell a friend.',
    momentPlaceholder: 'What happened…',
    momentKicker: 'The moment',
    whenTitle: 'When was this, roughly?',
    whenHint: 'A year is enough.',
    qBeginning: 'What was new here — what did this set in motion?',
    qBeginningHint: 'A first step, a break with the old, a change of course. Not the next step of something already underway.',
    qStake: 'What did it cost you to choose this, before you knew how it would go?',
    qStakeHint: 'Money, standing, comfort, a relationship, a version of yourself. “Nothing, really” is an honest answer too.',
    qReach: 'Who else felt it?',
    qReachHint: 'People whose world shifted, even slightly. If it stayed entirely inside you, leave this empty — that matters in its own way.',
    qHinge: 'Was there a day it showed on the outside?',
    qHingeHint: 'The call made, the flat emptied, the first morning back. Inner changes usually have one visible day.',
    skipQuestion: 'Skip',
    sensitiveTitle: 'Some moments shouldn’t be taken apart.',
    sensitiveBody: 'If you’d rather, this one can stay exactly as you wrote it — saved whole, private, off the arc, no questions asked.',
    sensitiveKeep: 'Keep it whole, privately',
    sensitiveContinue: 'I’d like to look at it',
    keepPrivate: 'Keep it off the arc — private, no glyph',
    keptConfirm: 'Kept, privately. No questions, no follow-up.',
    anonymousLabel: 'This deed was anonymous in the world',
    anonymousHint: 'The arc is where it gets signed. Only you will ever see it here.',
    placeAct: 'This has the shape of an act — it began something, it cost you something, and other people felt it.',
    placeActCaption: 'Acts are drawn as stars.',
    placeTurning: 'This has the shape of a turning — a hinge inside you. On the arc it stands with the same dignity as any star.',
    placeTurningCaption: 'Turnings are drawn as crescents.',
    placePhase: 'This sounds like a chapter of work — a bounded effort across months or years. Shall we lay it down as a line?',
    placeAnnouncement: 'This sounds like the announcement. The original moment — before it was safe to tell — is the act. Shall we log that moment instead?',
    placeGoodness: 'This doesn’t need the arc — and that’s exactly what makes it what it is.',
    placeGoodnessOffer: 'Keep it as a private note?',
    confirmAct: 'Set the star',
    confirmTurning: 'Set the crescent',
    confirmPhase: 'Lay the line',
    adjustPlacement: 'Place it differently',
    asAct: 'As an act',
    asActSub: 'a star — begun, risked, felt by others',
    asTurning: 'As a turning',
    asTurningSub: 'a crescent — an inward hinge',
    titleAsk: 'Give it a name for the arc',
    titleHint: 'Short, like a chapter heading.',
    selfCheck: 'It began something. Something real was at risk. Other people felt it. It cannot be taken back. If one of these is missing, this is not a star — place it differently, or keep it private. The arc is only as true as what you set in it.',
    stakeEmptyNote: 'The stake was left empty. If nothing was at risk, this may belong to the ground or to a line of work rather than the sky.',
  },

  // ── Declaration: the demanding coach ──
  declare: {
    title: 'Declare an act',
    intro: 'Four tests, a date, a witness. Declared acts are rare on purpose — five at most may stand open.',
    qBeginning: 'What will this begin?',
    qBeginningHint: 'A beginning, not the next step of something already underway.',
    qStake: 'What is at risk — judged now, before you know how it goes?',
    qStakeHint: 'If nothing real is exposed, it isn’t an act yet.',
    qReach: 'Whose world does it reach, beyond your own?',
    qReachHint: 'An act lands among others. Name who will feel it.',
    qIrreversible: 'Once done, it can’t be taken back. What makes it so?',
    qIrreversibleHint: 'The word said, the letter sent, the door closed behind you.',
    dateTitle: 'By when?',
    dateHint: 'A declared act without a date is a wish.',
    exposureTitle: 'How exposed does this leave you?',
    exposureHint: '1 is a raised eyebrow. 5 is a changed life.',
    witnessTitle: 'Who will know you said you’d do this?',
    witnessHint: 'One human who can ask “did you do it?” outperforms any reminder. Name a witness.',
    witnessSkip: 'Declare without a witness',
    witnessSkipHint: 'Some acts are safest unwitnessed. That is allowed.',
    redirectNoStake: 'Nothing is at risk here — this looks like maintenance. Move it there?',
    redirectContinuation: 'This is the next step of {chapter}, not a beginning. File it under that phase?',
    redirectAfterSafe: 'Stake is judged before the outcome. Log the original moment instead?',
    capReached: 'Five declared acts already stand open. Complete one, or let one lapse, before declaring another.',
    capReview: 'See the five',
    confirm: 'Declare it',
    declared: 'Declared. A hollow star waits right of the now-line.',
    moveToGround: 'Move to the ground',
    fileUnderChapter: 'File it under the chapter',
    logPastInstead: 'Log the original moment',
    keepDeclaring: 'It stands — continue',
  },

  // ── Story card ──
  story: {
    beginning: 'What it began',
    stake: 'What was at risk',
    reach: 'Where it reached',
    irreversible: 'Why it can’t be taken back',
    beginningFuture: 'What it will begin',
    stakeFuture: 'What is at risk',
    reachFuture: 'Whose world it reaches',
    irreversibleFuture: 'Why there’ll be no taking it back',
    witness: 'Witness',
    witnesses: 'Witnesses',
    anonymous: 'Anonymous in the world — signed here.',
    reflection: 'Reflection',
    reflectionAsk: 'Written after. What do you know now that you didn’t before?',
    addReflection: 'Add a reflection',
    due: 'due',
    declaredOn: 'declared',
    done: 'It’s done',
    doneAsk: 'When did it happen?',
    lapse: 'Let it lapse',
    lapseConfirm: 'A lapsed act stays on the record, faint. Nothing is hidden, nothing is judged. Let it lapse?',
    lapsed: 'lapsed',
    filled: 'The star is filled.',
    edit: 'Edit the words',
    remove: 'Remove from the record',
    removeConfirm: 'The arc will forget this entry. You decide whether you do. Remove it?',
    fromChapter: 'arose from',
  },

  // ── Chapters ──
  chapters: {
    title: 'Chapters',
    subtitle: 'Life’s work — bounded fabrication that leaves durable things.',
    empty: 'No chapters yet. Work that spans months deserves a line of its own.',
    newChapter: 'Open a chapter',
    orderHint: 'Top of this list is drawn highest on the arc.',
    drawHigher: 'Draw higher',
    drawLower: 'Draw lower',
    name: 'Name the chapter',
    started: 'When did it open?',
    intendedEnd: 'When do you intend it to end?',
    intendedEndHint: 'Open-ended is allowed. Ends can move.',
    shipping: 'What will exist when this ends?',
    shippingHint: 'The durable thing — a book, a house, a practice, a company, a person raised. If you can’t say yet, that’s allowed; the line stays open-ended and the question will wait for you.',
    openEnded: 'open-ended',
    open: 'open',
    shipped: 'shipped',
    closed: 'closed',
    fallow: 'fallow',
    ship: 'Mark it shipped',
    shipAsk: 'What now exists?',
    shipPrompt: 'Every phase is done — the road is walked.',
    close: 'Close without shipping',
    closeHint: 'Closed is honest. Not everything ships, and the line remains.',
    declareFallow: 'Declare fallow',
    fallowName: 'Name the fallow, if you wish',
    fallowHint: 'Rest, recovery, waiting, tending elsewhere. Fallow is drawn matter, never a gap.',
    endFallow: 'The fallow has ended',
    reopen: 'Reopen',
    phasesTitle: 'Phases',
    phasesHint: 'The road through the chapter, in order. Every phase is drawn on the line — undated ones evenly spaced until you give them a date.',
    addPhase: 'Add a phase',
    phaseName: 'Name the phase',
    phaseTarget: 'Target date',
    phaseCurrent: 'current',
    phaseDone: 'Mark the phase done',
    phaseDoneAt: 'done',
    stepsTitle: 'Steps',
    addStep: 'Add a step',
    stepPlaceholder: 'The next concrete thing…',
    quarterlyTitle: 'A quarter has passed',
    quarterlyBody: 'A quiet look at the lines. Close what ended, open what began, declare fallow where that’s the truth.',
    quarterlyShipping: 'still has no answer to “what will exist when this ends?”',
    quarterlyLater: 'Not now',
    quarterlyDone: 'The lines are true',
  },

  // ── Maintenance: the ground ──
  ground: {
    title: 'The ground',
    subtitle: 'What keeps the rest possible.',
    clear: 'clear',
    cleared: 'cleared',
    oneOffTitle: 'One-offs',
    oneOffHint: 'Done once, then gone. Cleared ones stay as texture on the ground.',
    addItem: 'Add a one-off',
    itemName: 'A chore, an errand — name it plainly',
    ritualTitle: 'Rituals',
    ritualHint: 'Repeats on a rhythm — daily, weekly, monthly',
    addRitual: 'Add a ritual',
    cadenceDaily: 'daily',
    cadenceWeekly: 'weekly',
    cadenceMonthly: 'monthly',
    // Completing everything produces silence. There is deliberately no
    // string for the all-clear state.
    emptyGround: 'The ground is bare. Add what you tend so the arc can show its rhythm.',
    removeItem: 'Remove',
    removeRitualConfirm: 'Remove the ritual “{name}”? Its kept days stay on the ground.',
  },

  // ── The Mirror ──
  mirror: {
    title: 'The Mirror',
    weekOf: 'Week of',
    notYet: 'The Mirror opens on {day}. Scarcity preserves its weight.',
    attention: 'Where the week went',
    attentionGround: 'ground tended',
    attentionLines: 'lines advanced',
    attentionSky: 'reached the arc',
    openLoops: 'Open loops',
    openLoopDue: 'due {date}',
    arcAdditions: 'What reached the arc',
    nothingReached: 'Nothing reached the arc this week.',
    pastMirrors: 'Past mirrors',
    times: '×',
  },

  // ── The Library ──
  library: {
    title: 'The Library',
    subtitle: 'Acts people have done with no money, no authority, and no audience. Organised by family. Exposure marked 1–5.',
    familyRepair: 'Repair',
    familySpeech: 'Speech',
    familyPromise: 'Promise',
    familyConvening: 'Convening',
    familyAsking: 'Asking',
    familyRefusal: 'Refusal',
    familyCare: 'Care',
    contrastTitle: 'Contrast pairs',
    contrastSubtitle: 'The same territory, a world apart. What separates them is always one of the four tests.',
    counterfeitTitle: 'Counterfeits',
    counterfeitSubtitle: 'Close relatives of the act, each failing one test. Naming the failing test is the whole lesson.',
    exposure: 'exposure',
    failsTest: 'the failing test',
    declareThis: 'Declare something like this',
  },

  // ── Onboarding ──
  onboarding: {
    coldOpen: 'Think of five moments in your life you’re proud of.',
    coldOpenHint: 'Anything that still feels like it mattered — big or small, public or private. A line each. Five if they come; even one is enough.',
    momentPlaceholder: 'A moment…',
    continueBtn: 'Continue',
    priming: 'Pride is a good compass. Inside proud moments there are usually beginnings — a day you started something, risked something, reached someone. Beginnings are rare; years can pass between them. That’s a life, not a failure. Let’s look at each of your five closely.',
    findThem: 'Look closely',
    excavateProgress: 'Moment {n} of {total}',
    revealCue: 'Your arc is ready.',
    drawIt: 'Draw it',
    rememberersTitle: 'Who could tell your story?',
    rememberersHint: 'Up to three people who hold pieces of it. Names stay on this device, like everything else.',
    rememberersSkip: 'No one comes to mind — continue',
    chapterTitle: 'Name the chapter you’re in',
    chapterHint: 'The work of this stretch of your life, in a line — “raising the kids”, “the second company”, “getting my health back”, “figuring out what’s next”.',
    chapterSkip: 'Between chapters — continue',
    firstActTitle: 'Declare one small act',
    firstActChapterLead: 'You called this chapter “{chapter}”.',
    firstActHint: 'One small thing you will actually do in the next two weeks — something that starts something, takes a pinch of courage, and touches at least one other person. It can live inside your chapter or entirely beside it.',
    firstActSmallNote: 'Keep it small — the kind of thing that risks a raised eyebrow, not a changed life.',
    firstActPlaceholder: 'I will…',
    firstActAiNote: 'Shaped around your chapter — pick one, or edit freely.',
    firstActSkip: 'Not yet — continue',
    seedRitual1: 'Morning walk',
    seedRitual2: 'Weekly reset',
    mirrorTitle: 'Pick a day for the Mirror',
    mirrorHint: 'Once a week, two minutes, a flat account of where the week went. Never more often.',
    finish: 'Open the arc',
  },

  // ── Settings ──
  settings: {
    title: 'Settings',
    privacyTitle: 'Where your words live',
    privacyBody: 'Everything you write stays on this device. There is no account, no server, no analytics, no trackers. The app keeps seven daily on-device safety copies. Export gives you everything as a file you own.',
    exportJson: 'Export everything (JSON)',
    exportTelling: 'Export the Telling (draft document)',
    importJson: 'Import from a file',
    importConfirm: 'Importing replaces what’s on this device with the file’s contents. Continue?',
    importDone: 'Imported.',
    importBad: 'That file doesn’t read as an Acts of Life export.',
    oldDataTitle: 'Previous telescope data',
    oldDataBody: 'Data from the earlier version of this app is still on this device, untouched. You can save it as a file.',
    oldDataExport: 'Export previous data (JSON)',
    mirrorDayTitle: 'Mirror day',
    textTitle: 'Text size',
    textDefault: 'Default',
    textLarge: 'Large',
    textLarger: 'Larger',
    aiTitle: 'A second reader',
    aiBody: 'Optional. With this on, the text of the entry you are working on is sent to Anthropic’s Claude to shape better questions and suggest placements — which you confirm or overrule. It never writes your entries; only your words are saved. Nothing else ever leaves this device. Off by default.',
    aiKeyLabel: 'Anthropic API key',
    aiKeyHint: 'Stored only on this device.',
    aiOn: 'Ask Claude during entry flows',
    aiTestOk: 'The key works.',
    aiTestBad: 'That key was refused.',
    aboutTitle: 'About',
    aboutBody: 'A reflection and story instrument, inspired by the work of Hannah Arendt. All words in the app are original.',
    replayTour: 'See the guide again',
    replayOnboarding: 'Run the beginning again',
    version: 'version',
  },

  kept: {
    title: 'Kept private',
    subtitle: 'Saved whole, off the arc. No glyph, no questions.',
    empty: 'Nothing here. Anything you choose to keep private — whole and unexamined — waits here, off the arc.',
  },

  telling: {
    draftTitle: 'The Telling — a draft',
    draftNote: 'Assembled from the record. The full Telling arrives with the year’s turn; this draft is yours to shape meanwhile.',
    chapterOpened: 'opened',
    chapterShipped: 'shipped —',
    fallowNamed: 'A fallow season',
  },

  common: {
    save: 'Save',
    cancel: 'Cancel',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    add: 'Add',
    today: 'today',
    year: 'Year',
    month: 'Month',
    day: 'Day',
    optional: 'optional',
    close: 'Close',
  },

  days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  months: ['January', 'February', 'March', 'April', 'May', 'June', 'July',
    'August', 'September', 'October', 'November', 'December'],
};
